# Generated by Django 3.0.5 on 2021-01-25 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20210124_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%y/%m/%d/', verbose_name='Фото'),
        ),
    ]
